# Generated by Django 3.2 on 2021-06-23 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software_under_testing',
            fields=[
                ('software_name', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='被测试软件名')),
                ('edition', models.CharField(max_length=20, verbose_name='版本号')),
                ('software_type', models.CharField(max_length=20, verbose_name='被测试软件类型')),
                ('software_data', models.FileField(upload_to='software')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '被测试软件',
                'verbose_name_plural': '被测试软件',
                'db_table': 'tb_software_under_testing',
            },
        ),
        migrations.CreateModel(
            name='Test_plan',
            fields=[
                ('plan_num', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='测试计划编号')),
                ('plan_title', models.CharField(max_length=30, verbose_name='测试计划标题')),
                ('plan_executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
                ('plan_software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.software_under_testing')),
            ],
        ),
    ]
