# Generated by Django 3.2 on 2021-06-23 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Software_under_testing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_name', models.CharField(max_length=50, unique=True, verbose_name='被测试软件名')),
                ('software_num', models.CharField(max_length=20, unique=True, verbose_name='被测试软件编号')),
                ('edition', models.CharField(max_length=20, verbose_name='版本号')),
                ('software_type', models.CharField(max_length=20, verbose_name='被测试软件类型')),
                ('software_data', models.FileField(upload_to='software')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '被测试软件',
                'verbose_name_plural': '被测试软件',
                'db_table': 'tb_software_under_testing',
                'unique_together': {('software_name', 'edition')},
            },
        ),
        migrations.CreateModel(
            name='Test_plan',
            fields=[
                ('plan_num', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='测试计划编号')),
                ('plan_title', models.CharField(max_length=30, verbose_name='测试计划标题')),
                ('plan_state', models.CharField(max_length=20, verbose_name='测试计划执行状态')),
                ('plan_desc', models.TextField(verbose_name='测试计划描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('test_report', models.FileField(upload_to='test_report')),
                ('plan_executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user', verbose_name='测试计划执行者')),
                ('plan_software', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.software_under_testing', verbose_name='测试软件名')),
            ],
            options={
                'verbose_name': '测试计划',
                'verbose_name_plural': '测试计划',
                'db_table': 'tb_test_plan',
            },
        ),
        migrations.CreateModel(
            name='Test_task',
            fields=[
                ('task_num', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='测试任务编号')),
                ('task_title', models.CharField(max_length=50, verbose_name='测试任务标题')),
                ('task_state', models.CharField(max_length=20, verbose_name='测试任务状态')),
                ('task_desc', models.TextField(verbose_name='测试任务描述')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('task_executor', models.ManyToManyField(to='user.User', verbose_name='测试任务执行者')),
                ('task_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.test_plan', verbose_name='测试任务所属计划')),
            ],
            options={
                'verbose_name': '测试任务',
                'verbose_name_plural': '测试任务',
                'db_table': 'tb_test_task',
            },
        ),
        migrations.CreateModel(
            name='Test_case',
            fields=[
                ('case_num', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='测试用例编号')),
                ('case_title', models.CharField(max_length=50, verbose_name='测试用例标题')),
                ('case_state', models.CharField(max_length=20, verbose_name='测试用例状态')),
                ('case_requisite', models.TextField(blank=True, verbose_name='测试输入项')),
                ('case_process', models.TextField(verbose_name='测试步骤')),
                ('expected_results', models.TextField(verbose_name='预期结果')),
                ('actual_results', models.TextField(verbose_name='实际结果')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('nothing', models.CharField(max_length=10, verbose_name='nothing')),
                ('case_assessor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_assessor', to='user.user', verbose_name='测试用例评审员')),
                ('case_executor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='case_executor', to='user.user', verbose_name='测试用例执行者')),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'db_table': 'tb_test_case',
            },
        ),
    ]
